Ya funciona la funcionalidad de verse como un popUp
PatoGuereque/Learn-to-Py pull request #10
Opened 2021-04-20 19:49 UTC by gabrielgomez99

nada mas es lo basico y ensena un template de las cosas que mostrara cada pop up

2021-04-20 21:26 UTC, PatoGuereque requested changes

2021-04-20 21:26 UTC, PatoGuereque commented on Learn-to-py/popUpEditarSeleccionCodigo.swift
> +class popUpEditarSeleccionCodigo: UIViewController {
igual aqui

2021-04-20 21:26 UTC, PatoGuereque commented on Learn-to-py/popUpEditar_i.swift
> +class popUpEditar_i: UIViewController {
igual aqui

2021-04-20 21:26 UTC, PatoGuereque commented on Learn-to-py/popUpEditarIterable.swift
> +class popUpEditarIterable: UIViewController {
Al ser una clase de Swift, se debe de seguir los estándares de nomenclatura, los cuales son UpperCamelCase (también llamada PascalCase) para el nombre de las clases/protocolos.

El nombre para esta clase sería ``PopUpEditarIterable`` en lugar de ``popUpEditarIterable``

2021-04-20 21:55 UTC, oscardavidrm reviewed
Va bien brou.

2021-04-20 21:55 UTC, oscardavidrm commented on Learn-to-py/popUpEditarIterable.swift
> +class popUpEditarIterable: UIViewController {
Las clases en Swift usan PascalCase. 👁️

2021-04-20 21:55 UTC, oscardavidrm commented on Learn-to-py/popUpEditar_i.swift
> +class popUpEditar_i: UIViewController {
Creo que estaría mejor si le cambias el nombre a `PopupEditVariable`, ya que la variable puede cambiar de nombre.

2021-04-20 21:55 UTC, oscardavidrm commented on Learn-to-py/popUpEditar_i.swift
> +    @IBOutlet weak var lb_i: UILabel!
Igual aquí, `labelVariable`

2021-04-21 02:43 UTC, PatoGuereque approved these changes
LGTM

2021-04-21 02:44 UTC, merged